<a href="https://colab.research.google.com/github/arman-hossain45/Natural_Language_-Processing/blob/main/text_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd

If there is a problem during the loading is happed then apply this formate

In [8]:
df = pd.read_csv("/content/IMDB Dataset.csv",
                 encoding='latin1',
                 engine='python',
                 on_bad_lines='skip'
                 )

In [9]:
df.shape

(50000, 2)

In [10]:
df.isnull()

       review  sentiment
0       False      False
1       False      False
2       False      False
3       False      False
4       False      False
...       ...        ...
49995   False      False
49996   False      False
49997   False      False
49998   False      False
49999   False      False

[50000 rows x 2 columns]

In [11]:
df.describe()

                                                   review sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

# convert lower case all text

In [17]:
df['review'][2].lower()

'i thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. the plot is simplistic, but the dialogue is witty and the characters are likable (even the well bread suspected serial killer). while some may be disappointed when they realize this is not match point 2: risk addiction, i thought it was proof that woody allen is still fully in control of the style many of us have grown to love.<br /><br />this was the most i\'d laughed at one of woody\'s comedies in years (dare i say a decade?). while i\'ve never been impressed with scarlet johanson, in this she managed to tone down her "sexy" image and jumped right into a average, but spirited young woman.<br /><br />this may not be the crown jewel of his career, but it was wittier than "devil wears prada" and more interesting than "superman" a great comedy to go see with friends.'

In [18]:
df['review'] = df['review'].str.lower()

In [19]:
df['review']

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. <br /><br />the...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

# HTMl tag remove

In [24]:
# we do it using function
import re
def remove_html_tag(text):
  pattern = re.compile(r"<.*?>")# mane holo shudu <> ai tuku select korbe bhitorer tuku select korbe na

  return pattern.sub(r'',text)

compile() একটি regex pattern কে compile করে রাখে যাতে বারবার ব্যবহার করলে দ্রুত কাজ করে।

In [25]:
remove_html_tag(df['review'][2])

'i thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. the plot is simplistic, but the dialogue is witty and the characters are likable (even the well bread suspected serial killer). while some may be disappointed when they realize this is not match point 2: risk addiction, i thought it was proof that woody allen is still fully in control of the style many of us have grown to love.this was the most i\'d laughed at one of woody\'s comedies in years (dare i say a decade?). while i\'ve never been impressed with scarlet johanson, in this she managed to tone down her "sexy" image and jumped right into a average, but spirited young woman.this may not be the crown jewel of his career, but it was wittier than "devil wears prada" and more interesting than "superman" a great comedy to go see with friends.'

In [26]:
df['review'] = df['review'].apply(remove_html_tag)

In [27]:
df['review']

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. the filming tec...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

# URL removal preocess
https?:\/\/\S+|www\.\S+

aikhan a muloto khujbe https then // khujbe jodi pay tahole white space ar ag pojonto select kore nai kore dibe www peleo same process a kaj korbe

In [28]:
text = 'hi my web link is https://www.google.com and https://www.facebook.com'

def remove_url(text):
  pattern = re.compile(r'https?://\S+|www\.\S+')
  return pattern.sub(r'',text)

In [29]:
text1 = remove_url(text)
text1

'hi my web link is  and '

In [30]:
df['review'] = df['review'].apply(remove_url)

In [31]:
df['review'].head(5)

0    one of the other reviewers has mentioned that ...
1    a wonderful little production. the filming tec...
2    i thought this was a wonderful way to spend ti...
3    basically there's a family where a little boy ...
4    petter mattei's "love in the time of money" is...
Name: review, dtype: object

# Remove punctuaation

In [32]:
import string

*way 01*

In [33]:
exclude = string.punctuation

In [34]:
exclude

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [37]:
def remove_pun(text):
  for char in exclude:
    text = text.replace(char,"")

  return text

remove_pun("hi, my name is arman hossain, and i was a brilliant student at a time ")

'hi my name is arman hossain and i was a brilliant student at a time '

**way 2**

more efficient way it is

In [36]:
def remove_pun1(text):
  return text.translate(str.maketrans(' ',' ',exclude))


remove_pun1("hi, my name is arman hossain, and i was a brilliant student at a time ")

'hi my name is arman hossain and i was a brilliant student at a time '

# handle special text

Like omg ,wlc, thx

In [38]:
# short words like this
chat_words = {
    "A3": "Anytime, Anywhere, Anyplace",
    "ADIH": "Another Day In Hell",
    "AFK": "Away From Keyboard",
    "AFAIK": "As Far As I Know",
    "ASAP": "As Soon As Possible",
    "ATK": "At The Keyboard",
    "ATM": "At The Moment",
    "BAE": "Before Anyone Else",
    "BAK": "Back At Keyboard",
    "BBL": "Be Back Later",
    "BBS": "Be Back Soon",
    "BFN": "Bye For Now",
    "B4N": "Bye For Now",
    "BRB": "Be Right Back",
    "BRUH": "Bro",
    "BRT": "Be Right There",
    "BSAAW": "Big Smile And A Wink",
    "BTW": "By The Way",
    "BWL": "Bursting With Laughter",
    "CSL": "Can’t Stop Laughing",
    "CU": "See You",
    "CUL8R": "See You Later",
    "CYA": "See You",
    "DM": "Direct Message",
    "FAQ": "Frequently Asked Questions",
    "FC": "Fingers Crossed",
    "FIMH": "Forever In My Heart",
    "FOMO": "Fear Of Missing Out",
    "FR": "For Real",
    "FWIW": "For What It's Worth",
    "FYP": "For You Page",
    "FYI": "For Your Information",
    "G9": "Genius",
    "GAL": "Get A Life",
    "GG": "Good Game",
    "GMTA": "Great Minds Think Alike",
    "GN": "Good Night",
    "GOAT": "Greatest Of All Time",
    "GR8": "Great!",
    "HBD": "Happy Birthday",
    "IC": "I See",
    "ICQ": "I Seek You",
    "IDC": "I Don’t Care",
    "IDK": "I Don't Know",
    "IFYP": "I Feel Your Pain",
    "ILU": "I Love You",
    "ILY": "I Love You",
    "IMHO": "In My Honest/Humble Opinion",
    "IMU": "I Miss You",
    "IMO": "In My Opinion",
    "IOW": "In Other Words",
    "IRL": "In Real Life",
    "IYKYK": "If You Know, You Know",
    "JK": "Just Kidding",
    "KISS": "Keep It Simple, Stupid",
    "L": "Loss",
    "L8R": "Later",
    "LDR": "Long Distance Relationship",
    "LMK": "Let Me Know",
    "LMAO": "Laughing My A** Off",
    "LOL": "Laughing Out Loud",
    "LTNS": "Long Time No See",
    "M8": "Mate",
    "MFW": "My Face When",
    "MID": "Mediocre",
    "MRW": "My Reaction When",
    "MTE": "My Thoughts Exactly",
    "NVM": "Never Mind",
    "NRN": "No Reply Necessary",
    "NPC": "Non-Player Character",
    "OIC": "Oh I See",
    "OP": "Overpowered",
    "POV": "Point Of View",
    "PRT": "Party",
    "PRW": "Parents Are Watching",
    "ROFL": "Rolling On The Floor Laughing",
    "ROFLOL": "Rolling On The Floor Laughing Out Loud",
    "ROTFLMAO": "Rolling On The Floor Laughing My A** Off",
    "RN": "Right Now",
    "SK8": "Skate",
    "SUS": "Suspicious",
    "TBH": "To Be Honest",
    "TFW": "That Feeling When",
    "THX": "Thank You",
    "TIME": "Tears In My Eyes",
    "TLDR": "Too Long, Didn’t Read",
    "TNTL": "Trying Not To Laugh",
    "TTFN": "Ta-Ta For Now!",
    "TTYL": "Talk To You Later",
    "U": "You",
    "U2": "You Too",
    "U4E": "Yours For Ever",
    "W": "Win",
    "W8": "Wait...",
    "WB": "Welcome Back",
    "WTG": "Way To Go!",
    "WUF": "Where Are You From?",
    "WYD": "What You Doing?",
    "WYWH": "Wish You Were Here",
    "ZZZ": "Sleeping, Bored, Tired",
    "OMG!": "Oh My God",
    "SMH": "Shaking My Head",
    "NGL": "Not Gonna Lie",
    "TBF": "To Be Fair",
    "ICYMI": "In Case You Missed It",
    "IMO": "In My Opinion",
    "IMHO": "In My Honest Opinion",
    "RN": "Right Now",
    "FR": "For Real",
    "DW": "Don't Worry",
    "ILYSM": "I Love You So Much",
    "OMW": "On My Way",
    "GGWP": "Good Game Well Played",
    "GG": "Good Game",
    "EZ": "Easy",
    "LMAO": "Laughing My A** Off",
    "LOL": "Laughing Out Loud"
}

In [43]:
def chat_conversation(text):
  new_text = []
  for w in text.split():
    if w.upper() in chat_words:# choto hater thakleo seta ke boro
    # hater digit a convert kore list a append korbe
      new_text.append(chat_words[w.upper()])

    else :
      new_text.append(w)

  return " ".join(new_text)

In [42]:
chat_conversation('AFK omg!')

'Away From Keyboard Oh My God'

# Spelling Mistake correction

In [46]:
# spell check
from textblob import TextBlob
incorrected_text = "good mornig this is Arman"
textblb = TextBlob(incorrected_text)
textblb.correct().string

'good morning this is Man'

search : spell corection using nltk python

# Stopwords remove

Stop Words কী?

Stop Words হলো এমন কিছু সাধারণ শব্দ, যেগুলো একটি বাক্যে খুব বেশি ব্যবহৃত হয় কিন্তু সাধারণত বাক্যের মূল অর্থ বোঝার জন্য খুব বেশি গুরুত্বপূর্ণ নয়।

উদাহরণ (English):

I am going to school

এখানে:

I
am
to

এগুলো Stop Words হতে পারে।

আর

going
school

এগুলো গুরুত্বপূর্ণ শব্দ।

In [47]:
import nltk

In [50]:
from nltk.corpus import stopwords

nltk.download('stopwords')
stopwords.words('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [54]:
stops_words = set(stopwords.words('english'))

def remove_stopwords(text):
  words = text.split()
  cleaned = []
  for word in words:
    # word convert in lower text
    word = word.lower().strip(string.punctuation)
    #punctuation thakle tao remove kore dibe aikhan a
    if word and word not in stops_words:
      cleaned.append(word)

  return " ".join(cleaned)

In [55]:
remove_stopwords('i am going, to school')

'going school'

In [60]:
df['review']=df['review'].apply(remove_stopwords)
df['review']

0        one reviewers mentioned watching 1 oz episode ...
1        wonderful little production filming technique ...
2        thought wonderful way spend time hot summer we...
3        basically there's family little boy jake think...
4        petter mattei's love time money visually stunn...
                               ...
49995    thought movie right good job creative original...
49996    bad plot bad dialogue bad acting idiotic direc...
49997    catholic taught parochial elementary schools n...
49998    going disagree previous comment side maltin on...
49999    one expects star trek movies high art fans exp...
Name: review, Length: 50000, dtype: object

# Remove Emoji  in text

In [64]:
text_With_emoji ="""Hey! 😊 How are you doing today? 🌞
I'm feeling great 😄 and ready to learn some Python 🐍💻."""

In [62]:
import re

def remove_emoji(text):
  emoji_pattern = re.compile("["# emoji unicode range
                               u"\U0001F600-\U0001F64F"  # emoticons
                               u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                               u"\U0001F680-\U0001F6FF"  # transport & map symbols
                               u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                               u"\U00002702-\U000027B0"
                               u"\U000024C2-\U0001F251"
                               "]+",
                              flags=re.UNICODE)
  return emoji_pattern.sub(r'',text)

In [66]:
clean_text = remove_emoji(text_With_emoji)
clean_text

"Hey!  How are you doing today? \nI'm feeling great  and ready to learn some Python ."

In [67]:
df['review'] = df['review'].apply(remove_emoji)
df['review']

0        one reviewers mentioned watching 1 oz episode ...
1        wonderful little production filming technique ...
2        thought wonderful way spend time hot summer we...
3        basically there's family little boy jake think...
4        petter mattei's love time money visually stunn...
                               ...
49995    thought movie right good job creative original...
49996    bad plot bad dialogue bad acting idiotic direc...
49997    catholic taught parochial elementary schools n...
49998    going disagree previous comment side maltin on...
49999    one expects star trek movies high art fans exp...
Name: review, Length: 50000, dtype: object

# Tokenization using nltk and spacy

In [68]:
#NLTK
from nltk.tokenize import word_tokenize,sent_tokenize
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [69]:
sent1 = 'I am going to visit dhaka'
word_tokenize(sent1)

['I', 'am', 'going', 'to', 'visit', 'dhaka']

In [75]:
text = """ Hi my name is ARMAN. I am a running fourth year student .
Recently ,I work in a project."""

In [76]:
sent_tokenize(text)

[' Hi my name is ARMAN.',
 'I am a running fourth year student .',
 'Recently ,I work in a project.']

In [77]:
word_tokenize(text)

['Hi',
 'my',
 'name',
 'is',
 'ARMAN',
 '.',
 'I',
 'am',
 'a',
 'running',
 'fourth',
 'year',
 'student',
 '.',
 'Recently',
 ',',
 'I',
 'work',
 'in',
 'a',
 'project',
 '.']

Here is a some problem in tokenization it not convert all in a token some times do some mistakes

In [78]:
sent1= 'I have a Ph.D in A.I'
sent2= "We're here to help!  mail us at nks@gmail.com "
sent3 = "A 5km ride cost $10.50"

word_tokenize(sent3)

['A', '5km', 'ride', 'cost', '$', '10.50']

Here is rises this problem in this problem we  see that 5km is not separate as a token  so solve this problem we take spacy

In [82]:
word_tokenize(sent1)

['I', 'have', 'a', 'Ph.D', 'in', 'A.I']

In [79]:
import spacy
nlp = spacy.load('en_core_web_sm')

In [81]:
doc1 = nlp(sent1)
doc2 = nlp(sent2)
doc3 = nlp(sent3)
doc1

I have a Ph.D in A.I

In [83]:
for token in doc3:
  print(token)

A
5
km
ride
cost
$
10.50

# Stemming

simple word in bangla bhaga word ke bhagha

Stemming কী?

Stemming হলো NLP (Natural Language Processing)-এর একটি Text Preprocessing Technique, যেখানে একটি শব্দের বিভিন্ন রূপ (word forms) থেকে মূল অংশ (root/stem) বের করা হয়।

সহজ ভাষায়:

একটি শব্দের শেষে থাকা prefix/suffix কেটে শব্দটিকে তার মূল রূপের কাছাকাছি নিয়ে আসার প্রক্রিয়াকে Stemming বলে।

কেন Stemming দরকার?

ধরো নিচের শব্দগুলো আছে:

play
playing
played
plays

মানুষ বুঝতে পারে এগুলো একই শব্দ "play" থেকে এসেছে।

কিন্তু কম্পিউটার এগুলোকে ৪টি আলাদা শব্দ হিসেবে দেখে।

Stemming করলে:

play
playing  → play
played   → play
plays    → play

এখন সবগুলোকে একই শব্দ হিসেবে গণ্য করা যাবে।

In [84]:
from nltk.stem.porter import PorterStemmer

In [86]:
ps = PorterStemmer()
def stem_words(text):
  return " ".join([ps.stem(word) for word in text.split()])

In [87]:
sample = 'walk walks walking walked'
stem_words(sample)

'walk walk walk walk'

In [88]:
text = 'Probably my alltime favourite movie a story selflessness sacrifice and dedication to  be a good man and a good researcher'
stem_words(text)

'probabl my alltim favourit movi a stori selfless sacrific and dedic to be a good man and a good research'

Stemming is a many grammer mistake and this is not better  than Lemmtization formula

# LEMMTIZATION

In [89]:
from nltk.stem import WordNetLemmatizer

In [90]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [91]:
wordnet_lemmatizer = WordNetLemmatizer()
sentence = "He was running and eating at same time. He has bad habit of swimming after playing a long time"